version: "3.9"

services:
  web:
    build: .
    pull_policy: build
    image: seleftheraki/crps-rec:latest
    container_name: crps-rec
    restart: unless-stopped
    # ports:
      # - 80:80
    networks:
      - traefik
    env_file:
      - /Users/stavroula/Documents/PhD/Implementations/fc4eosc-recommender/.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.crps-rec.rule= Host(`test.darelab.athenarc.gr`) && PathPrefix(`/crps-rec`)

networks:
  traefik:
    name: traefik
    external: true
