from typing import Any, Dict

import pydantic
from pydantic import model_serializer


class ItemRecommendation(pydantic.BaseModel):
    """
    The **ItemRecommendation model** represents a recommended item generated by a recommender.
    It includes the id of the item and the score of the recommendation.

    **Example**
    ```python
    item_rec = ItemRecommendation(
                item_id=1,
                score=0.9,
            )
    ```

    **Arguments**

    * `item_id (Union[int, str])`: The unique identifier of the item.
    * `score (float)`: The score of the recommendation.
    """

    item_id: Any
    score: float

    model_config = pydantic.ConfigDict(
        extra="forbid"
    )  # allow only fields defined in the model

    @model_serializer
    def serialize_recommendation(self) -> Dict[str, Any]:
        return {"item_id": str(self.viewed_item_id), "score": str(self.score)}
